SELECT "COURSES"."NAME" AS "Course name",
	"STUDENTS"."FIRST_NAME" AS "First name",
	"STUDENTS"."LAST_NAME" AS "Last name"
FROM public."STUDENTS_COURSES_JUNCTION"
JOIN public."COURSES" ON "COURSES"."COURSE_ID" =
			"STUDENTS_COURSES_JUNCTION"."COURSES_ID"
JOIN public."STUDENTS" ON "STUDENTS"."STUDENT_ID" = 
			"STUDENTS_COURSES_JUNCTION"."STUDENTS_ID"