CREATE TABLE public."STUDENTS_COURSES_JUNCTION"
(
  "STUDENTS_ID" integer NOT NULL,
  "COURSES_ID" integer NOT NULL,
  CONSTRAINT "FK_COUR_ID" FOREIGN KEY ("COURSES_ID")
      REFERENCES public."COURSES" ("COURSE_ID") MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT "FK_STUD_ID" FOREIGN KEY ("STUDENTS_ID")
      REFERENCES public."STUDENTS" ("STUDENT_ID") MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public."STUDENTS_COURSES_JUNCTION"
  OWNER TO postgres;